import { type MiniApp } from '@/store/miniAppStore';

export const MINIAPPS: MiniApp[] = [
  {
    id: 'scrollswap',
    name: 'ScrollSwap',
    url: 'https://scrollswap.com',
    icon: '🔄',
    description: 'Trade tokens with zero slippage and best rates on Scroll',
    category: 'DeFi',
    featured: true,
    verified: true,
  },
  {
    id: 'zkpay',
    name: 'ZK Pay',
    url: 'https://zkpay.io',
    icon: '💳',
    description: 'Private payments powered by zero-knowledge proofs',
    category: 'Payments',
    featured: true,
    verified: true,
  },
  {
    id: 'scrollbridge',
    name: 'Scroll Bridge',
    url: 'https://scroll.io/bridge',
    icon: '🌉',
    description: 'Bridge assets between Ethereum and Scroll securely',
    category: 'Bridge',
    featured: true,
    verified: true,
  },
  {
    id: 'scrollnft',
    name: 'Scroll NFT',
    url: 'https://scrollnft.art',
    icon: '🎨',
    description: 'Create, buy, and sell NFTs on Scroll blockchain',
    category: 'NFT',
    featured: false,
    verified: true,
  },
  {
    id: 'scrolllend',
    name: 'Scroll Lend',
    url: 'https://scrolllend.finance',
    icon: '🏦',
    description: 'Lend and borrow crypto assets with competitive rates',
    category: 'DeFi',
    featured: true,
    verified: true,
  },
  {
    id: 'scrollgaming',
    name: 'Scroll Gaming',
    url: 'https://scrollgaming.io',
    icon: '🎮',
    description: 'Play blockchain games and earn rewards',
    category: 'Gaming',
    featured: false,
    verified: false,
  },
  {
    id: 'scrolldao',
    name: 'Scroll DAO',
    url: 'https://scrolldao.org',
    icon: '🗳️',
    description: 'Participate in Scroll governance and proposals',
    category: 'Governance',
    featured: false,
    verified: true,
  },
  {
    id: 'scrollsocial',
    name: 'Scroll Social',
    url: 'https://scrollsocial.app',
    icon: '💬',
    description: 'Decentralized social network built on Scroll',
    category: 'Social',
    featured: false,
    verified: false,
  },
  {
    id: 'scrollai',
    name: 'Scroll AI',
    url: 'https://scrollai.tech',
    icon: '🤖',
    description: 'AI-powered tools and assistants on Scroll',
    category: 'AI',
    featured: false,
    verified: true,
  },
  {
    id: 'scrollmusic',
    name: 'Scroll Music',
    url: 'https://scrollmusic.io',
    icon: '🎵',
    description: 'Stream and own music NFTs on Scroll',
    category: 'Entertainment',
    featured: false,
    verified: false,
  },
  {
    id: 'scrolllearn',
    name: 'Scroll Learn',
    url: 'https://scrolllearn.edu',
    icon: '📚',
    description: 'Educational platform with NFT certificates',
    category: 'Education',
    featured: false,
    verified: true,
  },
  {
    id: 'scrollhealth',
    name: 'Scroll Health',
    url: 'https://scrollhealth.care',
    icon: '🏥',
    description: 'Healthcare records on blockchain',
    category: 'Health',
    featured: false,
    verified: true,
  },
  {
    id: 'scrollpets',
    name: 'Scroll Pets',
    url: 'https://scrollpets.fun',
    icon: '🐾',
    description: 'Collect and trade virtual pets',
    category: 'Gaming',
    featured: false,
    verified: false,
  },
  {
    id: 'scrollphoto',
    name: 'Scroll Photo',
    url: 'https://scrollphoto.gallery',
    icon: '📸',
    description: 'Decentralized photo storage and sharing',
    category: 'Social',
    featured: false,
    verified: true,
  },
  {
    id: 'scrollvote',
    name: 'Scroll Vote',
    url: 'https://scrollvote.org',
    icon: '🗳️',
    description: 'Transparent voting powered by blockchain',
    category: 'Governance',
    featured: false,
    verified: true,
  },
  {
    id: 'scrolltickets',
    name: 'Scroll Tickets',
    url: 'https://scrolltickets.live',
    icon: '🎫',
    description: 'Buy and sell event tickets as NFTs',
    category: 'Entertainment',
    featured: false,
    verified: true,
  },
  {
    id: 'scrollfitness',
    name: 'Scroll Fitness',
    url: 'https://scrollfitness.fit',
    icon: '💪',
    description: 'Track fitness goals and earn rewards',
    category: 'Health',
    featured: false,
    verified: false,
  },
  {
    id: 'scrolltrade',
    name: 'Scroll Trade',
    url: 'https://scrolltrade.exchange',
    icon: '📈',
    description: 'Advanced trading tools and analytics',
    category: 'DeFi',
    featured: false,
    verified: true,
  },
  {
    id: 'scrollchat',
    name: 'Scroll Chat',
    url: 'https://scrollchat.app',
    icon: '💭',
    description: 'Private messaging with end-to-end encryption',
    category: 'Social',
    featured: false,
    verified: true,
  },
];

export function getMiniAppById(id: string): MiniApp | undefined {
  return MINIAPPS.find((app) => app.id === id);
}

export function getMiniAppsByCategory(category: string): MiniApp[] {
  return MINIAPPS.filter((app) => app.category === category);
}

export function getFeaturedMiniApps(): MiniApp[] {
  return MINIAPPS.filter((app) => app.featured);
}

export function getCategories(): string[] {
  const categories = new Set(MINIAPPS.map((app) => app.category));
  return Array.from(categories);
}
